# mybatis
mybatis.mapper-locations=mybatis-mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# thymeleaf
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/